- title: Algoritmeregister SaaS
  description: Eerste algoritmeregister SaaS oplossing, ontwikkeld door AI-startup Saidot in samenwerking met Gemeente Amsterdam en Helsinki.
  aanbieder: Saidot
  type: software as a service
  voorbeeld: https://algoritmeregister.amsterdam.nl/
  url: https://www.saidot.ai/
- title: Algoritmeregister Common Ground
  description: Common Ground algoritmeregister software op basis van open source CMS Bolt.
  aanbieder: 
  type: product
  url: 